# Generated by Django 5.0.4 on 2026-04-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=50)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('total_xp', models.IntegerField(default=0)),
                ('weekly_stars', models.IntegerField(default=0)),
                ('streak_count', models.IntegerField(default=0)),
                ('last_login_date', models.DateField(blank=True, null=True)),
                ('last_task_reset', models.DateField(blank=True, null=True)),
                ('weekly_stars_reset', models.DateField(blank=True, null=True)),
                ('unlocked_alpha_count', models.IntegerField(default=0)),
                ('unlocked_num_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
